### ISSUE TITLE
GNOME 40

### ISSUE THREAD

**Issue by wooque** [fthx/simple-task-bar#20] opened 2021-02-02 08:25 UTC
I'm testing GNOME 40 and extension is working, but opening extension settings don't. It crashes with
```
Gtk.BuilderError: /home/vuk/.local/share/gnome-shell/extensions/simple-task-bar@fthx/prefs.ui:55:1 Unhandled tag: <packing>

Stack trace:
  _init@/home/vuk/.local/share/gnome-shell/extensions/simple-task-bar@fthx/prefs.js:36:17
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  buildPrefsWidget@/home/vuk/.local/share/gnome-shell/extensions/simple-task-bar@fthx/prefs.js:10:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by fthx** [comment] 2021-02-02 09:00
Thanks for your BR.
Yes G40 would need new prefs UI...

It's planned I make another extension (this one rewritten) without prefs because I don't have the energy to modify all prefs UI. Maybe at the end of this week. I'll poke you about that.

**Comment by wooque** [comment] 2021-02-02 09:08
No problem, I was just reporting current state on GNOME 40, don't intend to use it, it won't ship until late March

**Comment by fthx** [comment] 2021-02-04 16:25
You can try this new one:
https://extensions.gnome.org/review/download/22135.shell-extension.zip
You can check the code here:
https://extensions.gnome.org/review/22135
And soon you'll find it here:
https://extensions.gnome.org/extension/4000/babar/

If you can test it running GNOME 40, it would be great. There's no prefs UI, so no problem here ;-) . You have some constants you can change in the code. I'll wait for Gtk4 prefs UI guidelines...

**Comment by fthx** [comment] 2021-02-04 18:50
Please use, if you have to:
https://extensions.gnome.org/review/download/22139.shell-extension.zip
I've solved some small bugs.

**Comment by wooque** [comment] 2021-02-04 23:48
Thanks for new extension.
I'm not able to build GNOME 40 anymore, and I reverted back to 3.38, so won't be able to test it.
I noticed bug when context menu is opened, that extra empty workspace disappears from titlebar

**Comment by wooque** [comment] 2021-02-05 00:24
I've managed to build GNOME 40 again, Babar is working fine, apart from that disappearing workspace indicator

**Comment by fthx** [comment] 2021-02-05 07:50
Ok, I've merged that in Babar repo. Thanks!
Could you tell me accurately how to reproduce the bad behaviour of Babar? (software and so on ?)

**Comment by wooque** [comment] 2021-02-05 10:16
I use Arch Linux and gnome-shell-40alfa from AUR to get GNOME 40.
That disappearing workspace indicator happened in any program when I right-click to show menu

**Comment by fthx** [comment] 2021-02-05 10:24
Ok I can reproduce without your patch.
I opened this thread for BaBar:
https://github.com/fthx/babar/issues/2

**Closed as completed by fthx** 2021-02-05 10:24 UTC
